export const GAMES = [
  { id: 'rps', label: 'Rock Paper Scissors', emoji: '✊', desc: 'Classic showdown against the bot!', color: '#3b82f6', category: 'chance' },
  { id: 'ssg', label: 'Split Steal Give Away', emoji: '💰', desc: 'Your custom game! Outsmart the bot to win the prize.', color: '#f59e0b', category: 'card' },
  { id: 'gtn', label: 'Guess The Number', emoji: '🔢', desc: "Crack the bot's number! Choose your difficulty!", color: '#22c55e', category: 'brain' },
  { id: 'gtn-hc', label: 'Hot or Cold', emoji: '🌡️', desc: 'Getting warmer or colder? Use the clues!', color: '#ef4444', category: 'brain' },
  { id: 'hol', label: 'Higher or Lower', emoji: '🃏', desc: 'Guess if the next card is higher or lower!', color: '#8b5cf6', category: 'card' },
  { id: 'dice', label: 'Dice Roll', emoji: '🎲', desc: 'Bet on the dice! Exact, Range, or Parity.', color: '#06b6d4', category: 'chance' },
  { id: 'coin', label: 'Coin Flip Streak', emoji: '🪙', desc: 'Call Heads or Tails. Build a streak to win!', color: '#f97316', category: 'chance' },
  { id: 'memory', label: 'Memory Match', emoji: '🧠', desc: 'Find all matching pairs! Fewest moves wins.', color: '#ec4899', category: 'brain' },
  { id: 'word', label: 'Word Scramble', emoji: '📚', desc: 'Unscramble the letters to guess the word!', color: '#14b8a6', category: 'brain' },
  { id: 'merge', label: 'Number Merge', emoji: '🔢', desc: 'Slide tiles to merge same numbers. Reach the goal!', color: '#f59e0b', category: 'classic' },
  { id: 'reaction', label: 'Reaction Time', emoji: '⚡', desc: 'Click as fast as you can when it turns green!', color: '#eab308', category: 'reflex' },
  { id: 'typing', label: 'Typing Speed', emoji: '⌨️', desc: 'Type each word as fast as you can!', color: '#8b5cf6', category: 'reflex' },
  { id: 'simon', label: 'Simon Says', emoji: '🎵', desc: 'Watch the sequence, then repeat it!', color: '#ef4444', category: 'reflex' },
  { id: 'slots', label: 'Slots', emoji: '🎰', desc: 'Spin the reels! Match symbols to win big!', color: '#f59e0b', category: 'chance' },
  { id: 'blackjack', label: 'Blackjack', emoji: '🃏', desc: 'Get as close to 21 as you can without going over!', color: '#22c55e', category: 'card' },
  { id: 'whack', label: 'Whack-a-Mole', emoji: '🔨', desc: 'Whack the moles as fast as you can!', color: '#8b5cf6', category: 'reflex' },
  { id: 'snake', label: 'Snake', emoji: '🐍', desc: "Eat food, grow longer, don't hit yourself!", color: '#22c55e', category: 'classic' },
  { id: 'tetris', label: 'Tetris', emoji: '🧱', desc: 'Stack blocks, clear lines, rack up points!', color: '#00d4ff', category: 'classic' },
  { id: 'breakout', label: 'Breakout', emoji: '🏓', desc: 'Smash all the bricks with the ball!', color: '#ff2d7b', category: 'classic' },
  { id: 'flappy', label: 'Flappy Bird', emoji: '🐦', desc: 'Tap to flap, dodge the pipes!', color: '#ffe600', category: 'classic' },
  { id: 'minesweeper', label: 'Minesweeper', emoji: '💣', desc: 'Clear the field without hitting a mine!', color: '#f97316', category: 'brain' },
  { id: 'lightsout', label: 'Lights Out', emoji: '💡', desc: 'Toggle lights to turn them all off!', color: '#ffe600', category: 'brain' },
  { id: 'mastermind', label: 'Mastermind', emoji: '🧠', desc: 'Crack the hidden code using logic and deduction!', color: '#b946ff', category: 'brain' },
  { id: 'dodge', label: 'Dodge', emoji: '🎮', desc: 'Move your orb to dodge the falling obstacles!', color: '#00d4ff', category: 'reflex' },
  { id: 'mergeblitz', label: 'Merge Blitz', emoji: '⚡', desc: 'Timed 2048! Chain merges for combo multipliers!', color: '#ffe600', category: 'brain' },
  { id: 'connect4', label: 'Connect Four', emoji: '🔴', desc: 'Drop discs to get four in a row against the AI!', color: '#1a47b8', category: 'card' },
  { id: 'sudoku', label: 'Sudoku', emoji: '🔢', desc: 'Fill the 9×9 grid with numbers 1-9!', color: '#22c55e', category: 'brain' },
  { id: 'mathdash', label: 'Math Dash', emoji: '➕', desc: 'Solve as many math problems as you can before time runs out!', color: '#b946ff', category: 'reflex' },
  { id: 'wordle', label: 'Wordle', emoji: '📝', desc: 'Guess the hidden word in limited tries!', color: '#14b8a6', category: 'brain' },
  { id: 'centipede', label: 'Centipede', emoji: '🐛', desc: 'Shoot the centipede! Destroy segments, dodge spiders!', color: '#ff2d7b', category: 'arcade' },
  { id: 'pong', label: 'Pong', emoji: '🏓', desc: 'Classic paddle duel! Beat the AI to 7 points!', color: '#ffffff', category: 'arcade' },
  { id: 'spaceinvaders', label: 'Space Invaders', emoji: '👾', desc: 'Shoot the alien fleet before they reach Earth!', color: '#00ff41', category: 'arcade' },
  { id: 'asteroids', label: 'Asteroids', emoji: '☄️', desc: 'Blast the asteroids! Navigate and survive!', color: '#00d4ff', category: 'arcade' },
  { id: 'fruitslice', label: 'Fruit Slice', emoji: '🍉', desc: 'Slice the fruits, dodge the bombs!', color: '#ff2d7b', category: 'arcade' },
  { id: 'pong-pvp', label: 'Pong PvP', emoji: '🏓', desc: 'Real-time 1v1 Pong! Race your opponent to 7 points!', color: '#00d4ff', category: 'pvp' },
  { id: 'typing-pvp', label: 'Typing PvP', emoji: '⌨️', desc: 'Race against a real player to type faster!', color: '#8b5cf6', category: 'pvp' },
  { id: 'rps-pvp', label: 'RPS PvP', emoji: '✊', desc: 'Real-time best-of-5 Rock Paper Scissors!', color: '#ff2d7b', category: 'pvp' },
]
