export const THEMES = {
  neon: {
    name: 'Neon Arcade',
    emoji: '💜',
    vars: {
      '--bg-dark': '#1a1033',
      '--bg-card': '#2a1f4e',
      '--bg-card-hover': '#352863',
      '--neon-pink': '#ff2d7b',
      '--neon-blue': '#00d4ff',
      '--neon-green': '#39ff14',
      '--neon-yellow': '#ffe600',
      '--neon-purple': '#b946ff',
      '--neon-orange': '#ff6b2b',
      '--text-light': '#f0e6ff',
      '--text-dim': '#9b8ec4',
    },
  },
  ocean: {
    name: 'Ocean',
    emoji: '🌊',
    vars: {
      '--bg-dark': '#0a1628',
      '--bg-card': '#0f2440',
      '--bg-card-hover': '#153055',
      '--neon-pink': '#ff6b9d',
      '--neon-blue': '#00b4d8',
      '--neon-green': '#48cae4',
      '--neon-yellow': '#90e0ef',
      '--neon-purple': '#0077b6',
      '--neon-orange': '#f77f00',
      '--text-light': '#caf0f8',
      '--text-dim': '#5e9cbf',
    },
  },
  retro: {
    name: 'Retro CRT',
    emoji: '📺',
    vars: {
      '--bg-dark': '#0d0d0d',
      '--bg-card': '#1a1a1a',
      '--bg-card-hover': '#252525',
      '--neon-pink': '#ff4444',
      '--neon-blue': '#00ff88',
      '--neon-green': '#33ff00',
      '--neon-yellow': '#ccff00',
      '--neon-purple': '#00cc66',
      '--neon-orange': '#ff8800',
      '--text-light': '#d4ffb8',
      '--text-dim': '#6b8c52',
    },
  },
  pastel: {
    name: 'Pastel Dream',
    emoji: '🍬',
    vars: {
      '--bg-dark': '#2d2438',
      '--bg-card': '#3d3250',
      '--bg-card-hover': '#4d4262',
      '--neon-pink': '#ff9ecf',
      '--neon-blue': '#89cff0',
      '--neon-green': '#a8e6a1',
      '--neon-yellow': '#fff1a8',
      '--neon-purple': '#c9a8ff',
      '--neon-orange': '#ffb88c',
      '--text-light': '#f5eeff',
      '--text-dim': '#a899bf',
    },
  },
  crimson: {
    name: 'Crimson',
    emoji: '🔥',
    vars: {
      '--bg-dark': '#1a0a0a',
      '--bg-card': '#2d1111',
      '--bg-card-hover': '#3d1a1a',
      '--neon-pink': '#ff3355',
      '--neon-blue': '#ff6644',
      '--neon-green': '#ffaa00',
      '--neon-yellow': '#ffcc33',
      '--neon-purple': '#cc2244',
      '--neon-orange': '#ff5522',
      '--text-light': '#ffe8e8',
      '--text-dim': '#bf7a7a',
    },
  },
  forest: {
    name: 'Forest',
    emoji: '🌲',
    vars: {
      '--bg-dark': '#0d1a0d',
      '--bg-card': '#1a2e1a',
      '--bg-card-hover': '#243d24',
      '--neon-pink': '#ff7eb3',
      '--neon-blue': '#66ccaa',
      '--neon-green': '#44dd44',
      '--neon-yellow': '#ccdd44',
      '--neon-purple': '#88bb66',
      '--neon-orange': '#ddaa33',
      '--text-light': '#d8f0d8',
      '--text-dim': '#7aa87a',
    },
  },
}

export const THEME_ORDER = ['neon', 'ocean', 'retro', 'pastel', 'crimson', 'forest']
