export const TYPING_SENTENCES = [
  'The quick brown fox jumps over the lazy dog',
  'Pack my box with five dozen liquor jugs',
  'How vexingly quick daft zebras jump',
  'The five boxing wizards jump quickly',
  'Sphinx of black quartz judge my vow',
  'Two driven jocks help fax my big quiz',
  'Crazy Frederick bought many very exquisite opal jewels',
  'We promptly judged antique ivory buckles for the next prize',
  'A mad boxer shot a quick gloved jab to the jaw',
  'The quick brown fox jumps over the lazy dog near the bank of the river',
  'Amazingly few discotheques provide jukeboxes',
  'Jackdaws love my big sphinx of quartz',
  'The job requires extra pluck and zeal from every young wage earner',
  'Jaded zombies acted quaintly but kept driving their oxen forward',
  'Pack my red box with five dozen liquor jugs',
  'The fox jumped quickly over the lazy brown dog',
  'A wizard quick study of levitation can baffle the sphinx',
  'Bright vixens jump dozy fowl quack',
  'Mr Jock TV quiz PhD bags few lynx',
  'The five boxing wizards jump quickly over the lazy dog',
  'Pack your box with five dozen red liquor jugs',
  'The quick onyx goblin jumps over the lazy dwarf',
  'Jaded zombies drove their oxen quickly to the farm',
  'The wizard quickly jinxed the gnomes before they fled',
  'A black dog sat patiently while the cat played around',
  'The jay pig fox zebra bounced my old car yesterday',
  'How quickly daft jumping zebras vex the brown fox',
  'The five bright wizards quickly jinxed the goblin pack',
  'Jack loves my big sphinx of black quartz very much',
  'The brown fox jumped over the lazy sleeping dog',
]
